### ISSUE TITLE
Clean Cash

### ISSUE THREAD

**Issue by tellfa** [Marchuck/Mateyko#2]
tnx for this library, i want use this library for download images and update images from server.
i have one question, how to clean cash images? 
for example i want download users avatar from server and show it. when update avatar image, clean old avatar image and show new image

please help me, tnx

**Comment by Marchuck** [comment]
Hello,
could you explain more about your problem? Currently, image caching is not supported. Calling again  Mateyko.with(activity)..into(imageView) does not make effect? Are you displaying images on recyclerView?
Regards

//UPDATE:
 on new branch I introduced Mateyko.withNewInstance(activity) optional to Mateyko.with(activity)
Please open issue in case of problems
I hope it helped
